INSERT INTO users(id,name,username,email) VALUES (1,'Leanne Graham','Bret','Sincere@april.biz');
INSERT INTO users(id,name,username,email) VALUES (2,'Ervin Howell','Antonette','Shanna@melissa.tv');
INSERT INTO users(id,name,username,email) VALUES (3,'Clementine Bauch','Samantha','Nathan@yesenia.net');
INSERT INTO users(id,name,username,email) VALUES (4,'Patricia Lebsack','Karianne','Julianne.OConner@kory.org');
INSERT INTO users(id,name,username,email) VALUES (5,'Chelsey Dietrich','Kamren','Lucio_Hettinger@annie.ca');
INSERT INTO users(id,name,username,email) VALUES (6,'Mrs. Dennis Schulist','Leopoldo_Corkery','Karley_Dach@jasper.info');
INSERT INTO users(id,name,username,email) VALUES (7,'Kurtis Weissnat','Elwyn.Skiles','Telly.Hoeger@billy.biz');
INSERT INTO users(id,name,username,email) VALUES (8,'Nicholas Runolfsdottir V','Maxime_Nienow','Sherwood@rosamond.me');
INSERT INTO users(id,name,username,email) VALUES (9,'Glenna Reichert','Delphine','Chaim_McDermott@dana.io');
INSERT INTO users(id,name,username,email) VALUES (10,'Clementina DuBuque','Moriah.Stanton','Rey.Padberg@karina.biz');